package lt.vu.dao.datamapper;

import lt.vu.entities.mybatis.UserSurvey;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface UserSurveyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_survey
     *
     * @mbg.generated Wed Mar 22 10:22:28 EET 2017
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("surveyId") Integer surveyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_survey
     *
     * @mbg.generated Wed Mar 22 10:22:28 EET 2017
     */
    int insert(UserSurvey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_survey
     *
     * @mbg.generated Wed Mar 22 10:22:28 EET 2017
     */
    List<UserSurvey> selectAll();
}