package lt.vu.dao.datamapper;

import lt.vu.entities.mybatis.PersonSurvey;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PersonSurveyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.person_survey
     *
     * @mbg.generated Wed Mar 22 10:22:28 EET 2017
     */
    int deleteByPrimaryKey(@Param("personId") Integer personId, @Param("surveyId") Integer surveyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.person_survey
     *
     * @mbg.generated Wed Mar 22 10:22:28 EET 2017
     */
    int insert(PersonSurvey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.person_survey
     *
     * @mbg.generated Wed Mar 22 10:22:28 EET 2017
     */
    List<PersonSurvey> selectAll();
}